### ISSUE TITLE
SSLError: [SSL: WRONG_VERSION_NUMBER] 

### ISSUE THREAD

**Issue by ammonite** [google/earthengine-api#96] opened 2019-07-13 10:33 UTC
ee.Initialize() return message:
**SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)**
My machine: Ubuntu 18.04, python 3.6.8

And some traceback:
SSLError                                  Traceback (most recent call last)
<ipython-input-4-99e03d56abd3> in <module>
----> 1 ee.Initialize()
~/miniconda3/lib/python3.6/site-packages/ee/__init__.py in Initialize(credentials, opt_url, use_cloud_api, cloud_api_key, http_transport, project)
    109       http_transport=http_transport)
    110   # Initialize the dynamically loaded functions on the objects that want them.
--> 111   ApiFunction.initialize()
    112   Element.initialize()
    113   Image.initialize()

**Comment by tylere** [comment] 2019-08-23 00:13
Could you confirm whether or not this is still occurring with the most recent version of the Earth Engine Python API?  See https://developers.google.com/earth-engine/python_install

**Comment by ammonite** [comment] 2020-01-01 03:13
> Could you confirm whether or not this is still occurring with the most recent version of the Earth Engine Python API? See https://developers.google.com/earth-engine/python_install

Thank you very much tylere.
I re-install gee using conda and the issue remain the same but (_ssl.c:1067)
Happy New Year!

**Comment by tylere** [comment] 2020-01-06 17:44
I am unable to reproduce your issue using Ubuntu 18.04. Below is the steps I took, along with details of the installation.

```
docker pull ubuntu:18.04
docker run -it ubuntu:18.04
apt update
apt upgrade
apt install wget
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
source /root/.bashrc
conda install -c conda-forge earthengine-api
python
import ee
ee.Authenticate()
ee.Initialize()
```


### Installation Details
<details>
    <summary>create docker ubuntu:18.04 container</summary>

    (base) tylere-macbookpro2:tylere tylere$ docker pull ubuntu:18.04
    18.04: Pulling from library/ubuntu
    Digest: sha256:250cc6f3f3ffc5cdaa9d8f4946ac79821aafb4d3afc93928f0de9336eba21aa4
    Status: Image is up to date for ubuntu:18.04
    docker.io/library/ubuntu:18.04

    (base) tylere-macbookpro2:tylere tylere$ docker run -it ubuntu:18.04

    root@fe8c9e1a78ad:/# apt update
    Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
    Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
    Get:3 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [6781 B]
    Get:4 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [761 kB]
    Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]        
    Get:6 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]       
    Get:7 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [795 kB]
    Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
    Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
    Get:10 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [19.2 kB]
    Get:11 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]           
    Get:12 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
    Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [10.8 kB]                                                
    Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [35.0 kB]                                                
    Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1324 kB]                                                  
    Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1072 kB]                                                      
    Get:17 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [4244 B]                                                 
    Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2496 B]                                                     
    Fetched 17.4 MB in 8s (2058 kB/s)                                                                                                         
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    All packages are up to date.
    root@fe8c9e1a78ad:/# apt upgrade
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Calculating upgrade... Done
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

</details>
<details>
    <summary>install wget</summary>

    root@fe8c9e1a78ad:/# apt install wget
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following additional packages will be installed:
    ca-certificates libpsl5 libssl1.1 openssl publicsuffix
    The following NEW packages will be installed:
    ca-certificates libpsl5 libssl1.1 openssl publicsuffix wget
    0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
    Need to get 2519 kB of archives.
    After this operation, 7000 kB of additional disk space will be used.
    Do you want to continue? [Y/n] y
    Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libssl1.1 amd64 1.1.1-1ubuntu2.1~18.04.5 [1300 kB]
    Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 openssl amd64 1.1.1-1ubuntu2.1~18.04.5 [613 kB]
    Get:3 http://archive.ubuntu.com/ubuntu bionic/main amd64 ca-certificates all 20180409 [151 kB]
    Get:4 http://archive.ubuntu.com/ubuntu bionic/main amd64 libpsl5 amd64 0.19.1-5build1 [41.8 kB]
    Get:5 http://archive.ubuntu.com/ubuntu bionic/main amd64 publicsuffix all 20180223.1310-1 [97.6 kB]
    Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 wget amd64 1.19.4-1ubuntu2.2 [316 kB]
    Fetched 2519 kB in 2s (1365 kB/s)       
    debconf: delaying package configuration, since apt-utils is not installed
    Selecting previously unselected package libssl1.1:amd64.
    (Reading database ... 4046 files and directories currently installed.)
    Preparing to unpack .../0-libssl1.1_1.1.1-1ubuntu2.1~18.04.5_amd64.deb ...
    Unpacking libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.5) ...
    Selecting previously unselected package openssl.
    Preparing to unpack .../1-openssl_1.1.1-1ubuntu2.1~18.04.5_amd64.deb ...
    Unpacking openssl (1.1.1-1ubuntu2.1~18.04.5) ...
    Selecting previously unselected package ca-certificates.
    Preparing to unpack .../2-ca-certificates_20180409_all.deb ...
    Unpacking ca-certificates (20180409) ...
    Selecting previously unselected package libpsl5:amd64.
    Preparing to unpack .../3-libpsl5_0.19.1-5build1_amd64.deb ...
    Unpacking libpsl5:amd64 (0.19.1-5build1) ...
    Selecting previously unselected package publicsuffix.
    Preparing to unpack .../4-publicsuffix_20180223.1310-1_all.deb ...
    Unpacking publicsuffix (20180223.1310-1) ...
    Selecting previously unselected package wget.
    Preparing to unpack .../5-wget_1.19.4-1ubuntu2.2_amd64.deb ...
    Unpacking wget (1.19.4-1ubuntu2.2) ...
    Setting up libpsl5:amd64 (0.19.1-5build1) ...
    Setting up publicsuffix (20180223.1310-1) ...
    Setting up libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.5) ...
    debconf: unable to initialize frontend: Dialog
    debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
    debconf: falling back to frontend: Readline
    debconf: unable to initialize frontend: Readline
    debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
    debconf: falling back to frontend: Teletype
    Setting up openssl (1.1.1-1ubuntu2.1~18.04.5) ...
    Setting up wget (1.19.4-1ubuntu2.2) ...
    Setting up ca-certificates (20180409) ...
    debconf: unable to initialize frontend: Dialog
    debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
    debconf: falling back to frontend: Readline
    debconf: unable to initialize frontend: Readline
    debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
    debconf: falling back to frontend: Teletype
    Updating certificates in /etc/ssl/certs...
    133 added, 0 removed; done.
    Processing triggers for libc-bin (2.27-3ubuntu1) ...
    Processing triggers for ca-certificates (20180409) ...
    Updating certificates in /etc/ssl/certs...
    0 added, 0 removed; done.
    Running hooks in /etc/ca-certificates/update.d...
    done.
</details>

<details>
    <summary>install miniconda</summary>

    root@fe8c9e1a78ad:/# wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    --2020-01-06 17:28:42--  https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.130.3, 104.16.131.3, 2606:4700::6810:8303, ...
    Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.130.3|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 71785000 (68M) [application/x-sh]
    Saving to: 'Miniconda3-latest-Linux-x86_64.sh'

    Miniconda3-latest-Linux-x86_64.sh  100%[===============================================================>]  68.46M  28.2MB/s    in 2.4s    

    2020-01-06 17:28:44 (28.2 MB/s) - 'Miniconda3-latest-Linux-x86_64.sh' saved [71785000/71785000]

    root@fe8c9e1a78ad:/# bash Miniconda3-latest-Linux-x86_64.sh

    Welcome to Miniconda3 4.7.12

    In order to continue the installation process, please review the license
    agreement.
    Please, press ENTER to continue
    >>> 
    ===================================
    Miniconda End User License Agreement
    ===================================

    Copyright 2015, Anaconda, Inc.

    All rights reserved under the 3-clause BSD License:

    Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are m
    et:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the d
    ocumentation and/or other materials provided with the distribution.
    * Neither the name of Anaconda, Inc. ("Anaconda, Inc.") nor the names of its contributors may be used to endorse or promote products deri
    ved from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMIT
    ED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ANACONDA, INC. BE L
    IABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUB
    STITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER 
    IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVI
    SED OF THE POSSIBILITY OF SUCH DAMAGE.

    Notice of Third Party Software Licenses
    =======================================

    Miniconda contains open source software packages from third parties. These are available on an "as is" basis and subject to their individua
    l license agreements. These licenses are available in Anaconda Distribution or at http://docs.anaconda.com/anaconda/pkg-docs. Any binary pa
    ckages of these third party tools you obtain via Anaconda Distribution are subject to their individual licenses as well as the Anaconda lic
    ense. Anaconda, Inc. reserves the right to change which third party tools are provided in Miniconda.

    Cryptography Notice
    ===================

    This distribution includes cryptographic software. The country in which you currently reside may have restrictions on the import, possessio
    n, use, and/or re-export to another country, of encryption software. BEFORE using any encryption software, please check your country's laws
    , regulations and policies concerning the import, possession, or use, and re-export of encryption software, to see if this is permitted. Se
    e the Wassenaar Arrangement http://www.wassenaar.org/ for more information.

    Anaconda, Inc. has self-classified this software as Export Commodity Control Number (ECCN) 5D992b, which includes mass market information s
    ecurity software using or performing cryptographic functions with asymmetric algorithms. No license is required for export of this software
    to non-embargoed countries. In addition, the Intel(TM) Math Kernel Library contained in Anaconda, Inc.'s software is classified by Intel(T
    M) as ECCN 5D992b with no license required for export to non-embargoed countries.

    The following packages are included in this distribution that relate to cryptography:

    openssl
        The OpenSSL Project is a collaborative effort to develop a robust, commercial-grade, full-featured, and Open Source toolkit implementin
    g the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols as well as a full-strength general purpose cryptography libra
    ry.

    pycrypto
        A collection of both secure hash functions (such as SHA256 and RIPEMD160), and various encryption algorithms (AES, DES, RSA, ElGamal, e
    tc.).

    pyopenssl
        A thin Python wrapper around (a subset of) the OpenSSL library.

    kerberos (krb5, non-Windows platforms)
        A network authentication protocol designed to provide strong authentication for client/server applications by using secret-key cryptogr
    aphy.

    cryptography
        A Python library which exposes cryptographic recipes and primitives.


    Do you accept the license terms? [yes|no]
    [no] >>> yes

    Miniconda3 will now be installed into this location:
    /root/miniconda3

    - Press ENTER to confirm the location
    - Press CTRL-C to abort the installation
    - Or specify a different location below

    [/root/miniconda3] >>> 
    PREFIX=/root/miniconda3
    Unpacking payload ...
    Collecting package metadata (current_repodata.json): done                                                                                  
    Solving environment: done

    ## Package Plan ##

    environment location: /root/miniconda3

    added / updated specs:
        - _libgcc_mutex==0.1=main
        - asn1crypto==1.2.0=py37_0
        - ca-certificates==2019.10.16=0
        - certifi==2019.9.11=py37_0
        - cffi==1.13.0=py37h2e261b9_0
        - chardet==3.0.4=py37_1003
        - conda-package-handling==1.6.0=py37h7b6447c_0
        - conda==4.7.12=py37_0
        - cryptography==2.8=py37h1ba5d50_0
        - idna==2.8=py37_0
        - libedit==3.1.20181209=hc058e9b_0
        - libffi==3.2.1=hd88cf55_4
        - libgcc-ng==9.1.0=hdf63c60_0
        - libstdcxx-ng==9.1.0=hdf63c60_0
        - ncurses==6.1=he6710b0_1
        - openssl==1.1.1d=h7b6447c_3
        - pip==19.3.1=py37_0
        - pycosat==0.6.3=py37h14c3975_0
        - pycparser==2.19=py37_0
        - pyopenssl==19.0.0=py37_0
        - pysocks==1.7.1=py37_0
        - python==3.7.4=h265db76_1
        - readline==7.0=h7b6447c_5
        - requests==2.22.0=py37_0
        - ruamel_yaml==0.15.46=py37h14c3975_0
        - setuptools==41.4.0=py37_0
        - six==1.12.0=py37_0
        - sqlite==3.30.0=h7b6447c_0
        - tk==8.6.8=hbc83047_0
        - tqdm==4.36.1=py_0
        - urllib3==1.24.2=py37_0
        - wheel==0.33.6=py37_0
        - xz==5.2.4=h14c3975_4
        - yaml==0.1.7=had09818_2
        - zlib==1.2.11=h7b6447c_3


    The following NEW packages will be INSTALLED:

    _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
    asn1crypto         pkgs/main/linux-64::asn1crypto-1.2.0-py37_0
    ca-certificates    pkgs/main/linux-64::ca-certificates-2019.10.16-0
    certifi            pkgs/main/linux-64::certifi-2019.9.11-py37_0
    cffi               pkgs/main/linux-64::cffi-1.13.0-py37h2e261b9_0
    chardet            pkgs/main/linux-64::chardet-3.0.4-py37_1003
    conda              pkgs/main/linux-64::conda-4.7.12-py37_0
    conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.6.0-py37h7b6447c_0
    cryptography       pkgs/main/linux-64::cryptography-2.8-py37h1ba5d50_0
    idna               pkgs/main/linux-64::idna-2.8-py37_0
    libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
    libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
    libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
    libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
    ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
    openssl            pkgs/main/linux-64::openssl-1.1.1d-h7b6447c_3
    pip                pkgs/main/linux-64::pip-19.3.1-py37_0
    pycosat            pkgs/main/linux-64::pycosat-0.6.3-py37h14c3975_0
    pycparser          pkgs/main/linux-64::pycparser-2.19-py37_0
    pyopenssl          pkgs/main/linux-64::pyopenssl-19.0.0-py37_0
    pysocks            pkgs/main/linux-64::pysocks-1.7.1-py37_0
    python             pkgs/main/linux-64::python-3.7.4-h265db76_1
    readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
    requests           pkgs/main/linux-64::requests-2.22.0-py37_0
    ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.46-py37h14c3975_0
    setuptools         pkgs/main/linux-64::setuptools-41.4.0-py37_0
    six                pkgs/main/linux-64::six-1.12.0-py37_0
    sqlite             pkgs/main/linux-64::sqlite-3.30.0-h7b6447c_0
    tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
    tqdm               pkgs/main/noarch::tqdm-4.36.1-py_0
    urllib3            pkgs/main/linux-64::urllib3-1.24.2-py37_0
    wheel              pkgs/main/linux-64::wheel-0.33.6-py37_0
    xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
    yaml               pkgs/main/linux-64::yaml-0.1.7-had09818_2
    zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


    Preparing transaction: done
    Executing transaction: done
    installation finished.
    Do you wish the installer to initialize Miniconda3
    by running conda init? [yes|no]
    [no] >>> yes
    no change     /root/miniconda3/condabin/conda
    no change     /root/miniconda3/bin/conda
    no change     /root/miniconda3/bin/conda-env
    no change     /root/miniconda3/bin/activate
    no change     /root/miniconda3/bin/deactivate
    no change     /root/miniconda3/etc/profile.d/conda.sh
    no change     /root/miniconda3/etc/fish/conf.d/conda.fish
    no change     /root/miniconda3/shell/condabin/Conda.psm1
    no change     /root/miniconda3/shell/condabin/conda-hook.ps1
    no change     /root/miniconda3/lib/python3.7/site-packages/xontrib/conda.xsh
    no change     /root/miniconda3/etc/profile.d/conda.csh
    modified      /root/.bashrc

    ==> For changes to take effect, close and re-open your current shell. <==

    If you'd prefer that conda's base environment not be activated on startup, 
    set the auto_activate_base parameter to false: 

    conda config --set auto_activate_base false

    Thank you for installing Miniconda3!
    root@fe8c9e1a78ad:/# source /root/.bashrc

</details>
<details>
    <summary>install the Earth Engine Python API</summary>


    (base) root@fe8c9e1a78ad:/# conda install -c conda-forge earthengine-api
    Collecting package metadata (current_repodata.json): done
    Solving environment: done


    ==> WARNING: A newer version of conda exists. <==
    current version: 4.7.12
    latest version: 4.8.1

    Please update conda by running

        $ conda update -n base -c defaults conda



    ## Package Plan ##

    environment location: /root/miniconda3

    added / updated specs:
        - earthengine-api


    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        ca-certificates-2019.11.28 |       hecc5488_0         145 KB  conda-forge
        cachetools-3.1.1           |             py_0          11 KB  conda-forge
        certifi-2019.11.28         |           py37_0         148 KB  conda-forge
        conda-4.8.0                |           py37_1         3.0 MB  conda-forge
        earthengine-api-0.1.209    |             py_0         127 KB  conda-forge
        future-0.18.2              |           py37_0         711 KB  conda-forge
        google-api-core-1.15.0     |           py37_0          81 KB  conda-forge
        google-api-python-client-1.7.11|             py_0          43 KB  conda-forge
        google-auth-1.10.0         |             py_0          47 KB  conda-forge
        google-auth-httplib2-0.0.3 |             py_2          11 KB  conda-forge
        google-cloud-core-1.1.0    |             py_0          24 KB  conda-forge
        google-cloud-storage-1.23.0|           py37_0          89 KB  conda-forge
        google-resumable-media-0.5.0|             py_0          31 KB  conda-forge
        googleapis-common-protos-1.6.0|           py37_0          63 KB  conda-forge
        httplib2-0.15.0            |           py37_0         116 KB  conda-forge
        libprotobuf-3.11.2         |       h8b12597_0         4.8 MB  conda-forge
        openssl-1.1.1d             |       h516909a_0         2.1 MB  conda-forge
        protobuf-3.11.2            |   py37he1b5a44_0         700 KB  conda-forge
        pyasn1-0.4.8               |             py_0          53 KB  conda-forge
        pyasn1-modules-0.2.7       |             py_0          60 KB  conda-forge
        pytz-2019.3                |             py_0         237 KB  conda-forge
        rsa-4.0                    |             py_0          27 KB  conda-forge
        simplejson-3.17.0          |   py37h516909a_0         101 KB  conda-forge
        uritemplate-3.0.1          |             py_0          16 KB  conda-forge
        ------------------------------------------------------------
                                            Total:        12.7 MB

    The following NEW packages will be INSTALLED:

    cachetools         conda-forge/noarch::cachetools-3.1.1-py_0
    earthengine-api    conda-forge/noarch::earthengine-api-0.1.209-py_0
    future             conda-forge/linux-64::future-0.18.2-py37_0
    google-api-core    conda-forge/linux-64::google-api-core-1.15.0-py37_0
    google-api-python~ conda-forge/noarch::google-api-python-client-1.7.11-py_0
    google-auth        conda-forge/noarch::google-auth-1.10.0-py_0
    google-auth-httpl~ conda-forge/noarch::google-auth-httplib2-0.0.3-py_2
    google-cloud-core  conda-forge/noarch::google-cloud-core-1.1.0-py_0
    google-cloud-stor~ conda-forge/linux-64::google-cloud-storage-1.23.0-py37_0
    google-resumable-~ conda-forge/noarch::google-resumable-media-0.5.0-py_0
    googleapis-common~ conda-forge/linux-64::googleapis-common-protos-1.6.0-py37_0
    httplib2           conda-forge/linux-64::httplib2-0.15.0-py37_0
    libprotobuf        conda-forge/linux-64::libprotobuf-3.11.2-h8b12597_0
    protobuf           conda-forge/linux-64::protobuf-3.11.2-py37he1b5a44_0
    pyasn1             conda-forge/noarch::pyasn1-0.4.8-py_0
    pyasn1-modules     conda-forge/noarch::pyasn1-modules-0.2.7-py_0
    pytz               conda-forge/noarch::pytz-2019.3-py_0
    rsa                conda-forge/noarch::rsa-4.0-py_0
    simplejson         conda-forge/linux-64::simplejson-3.17.0-py37h516909a_0
    uritemplate        conda-forge/noarch::uritemplate-3.0.1-py_0

    The following packages will be UPDATED:

    ca-certificates    pkgs/main::ca-certificates-2019.10.16~ --> conda-forge::ca-certificates-2019.11.28-hecc5488_0
    certifi               pkgs/main::certifi-2019.9.11-py37_0 --> conda-forge::certifi-2019.11.28-py37_0
    conda                      pkgs/main::conda-4.7.12-py37_0 --> conda-forge::conda-4.8.0-py37_1

    The following packages will be SUPERSEDED by a higher-priority channel:

    openssl              pkgs/main::openssl-1.1.1d-h7b6447c_3 --> conda-forge::openssl-1.1.1d-h516909a_0


    Proceed ([y]/n)? yes


    Downloading and Extracting Packages
    simplejson-3.17.0    | 101 KB    | ################################################################################################ | 100% 
    earthengine-api-0.1. | 127 KB    | ################################################################################################ | 100% 
    protobuf-3.11.2      | 700 KB    | ################################################################################################ | 100% 
    google-cloud-storage | 89 KB     | ################################################################################################ | 100% 
    google-auth-httplib2 | 11 KB     | ################################################################################################ | 100% 
    google-cloud-core-1. | 24 KB     | ################################################################################################ | 100% 
    google-api-python-cl | 43 KB     | ################################################################################################ | 100% 
    ca-certificates-2019 | 145 KB    | ################################################################################################ | 100% 
    future-0.18.2        | 711 KB    | ################################################################################################ | 100% 
    httplib2-0.15.0      | 116 KB    | ################################################################################################ | 100% 
    pyasn1-modules-0.2.7 | 60 KB     | ################################################################################################ | 100% 
    conda-4.8.0          | 3.0 MB    | ################################################################################################ | 100% 
    pyasn1-0.4.8         | 53 KB     | ################################################################################################ | 100% 
    certifi-2019.11.28   | 148 KB    | ################################################################################################ | 100% 
    google-auth-1.10.0   | 47 KB     | ################################################################################################ | 100% 
    uritemplate-3.0.1    | 16 KB     | ################################################################################################ | 100% 
    libprotobuf-3.11.2   | 4.8 MB    | ################################################################################################ | 100% 
    rsa-4.0              | 27 KB     | ################################################################################################ | 100% 
    cachetools-3.1.1     | 11 KB     | ################################################################################################ | 100% 
    openssl-1.1.1d       | 2.1 MB    | ################################################################################################ | 100% 
    pytz-2019.3          | 237 KB    | ################################################################################################ | 100% 
    google-resumable-med | 31 KB     | ################################################################################################ | 100% 
    google-api-core-1.15 | 81 KB     | ################################################################################################ | 100% 
    googleapis-common-pr | 63 KB     | ################################################################################################ | 100% 
    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done

</details>
<details>
    <summary>Initialize the Earth Engine API</summary>

    (base) root@fe8c9e1a78ad:/# python
    Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> ee.Authenticate()
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    NameError: name 'ee' is not defined
    >>> import ee
    >>> ee.Authenticate()
    To authorize access needed by Earth Engine, open the following URL in a web browser and follow the instructions. If the web browser does not start automatically, please manually browse the URL below.

        https://accounts.google.com/o/oauth2/auth?client_id=517222506229-vsmmajv00ul0bs7p89v5m89qs8eb9359.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fearthengine+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code

    The authorization workflow will generate a code, which you should paste in the box below. 
    Enter verification code: 4/vAEnJri7UZn21DoHZbUc2_J-eQxjtBYmGeBPFGPKzFpa5dZBtGKIw2E

    Successfully saved authorization token.
    >>> ee.Initialize()
    >>> 
</details>

**Comment by ammonite** [comment] 2020-01-09 03:38
Thank you very much for your help, it is more than solving my problem. 
The issue may be caused by VPN installed on my machine for cope with censoship in China.

**Comment by tylere** [comment] 2020-01-09 05:13
Closing this issue because of the inability to reproduce the issue, and that it may be caused by the use of a VPN.

**Closed by tylere** 2020-01-09 05:13 UTC
Labels: need more info
