### ISSUE TITLE
JS API Timeouts preventing node to finalize

### ISSUE THREAD

**Issue by lleirborras** [google/earthengine-api#77] opened 2019-02-06 21:24 UTC
Since I started using the nodejs API to execute some scripts I realized the node process was never ending. After looking into it for a little bit I realized it is related to some **setTimeout** calls that are running behind the scenes, for example if usint the **authenticateViaPRivateKey** method an autorefresh mechanisms is instantiated using the **setTimeout** and making the process to never end

**Comment by donmccurdy** [comment] 2019-02-06 21:47
Could you share an example to help reproduce this? 

> for example if usint the **authenticateViaPRivateKey** method an autorefresh mechanisms is instantiated using the **setTimeout** and making the process to never end

Are you comparing auth via private key to some other auth method in Node.js and seeing the problem only in one case? Or just mentioning that the setTimeout is related to the private key authentication?

**Comment by lleirborras** [comment] 2019-02-07 08:00
just create a `test.js` file with the following content
```
this._ee = require('@google/earthengine');

const privateKey = require('./config/privatekey.json');
this._ee.data.authenticateViaPrivateKey(
    privateKey, 
    () => {console.log('Authentication done')},
    (e) => {console.log('Authentication error ' + e)},
);


console.log('fooo');
```
and execute `node test.js` , you will see that the messages arrive as expected and after that the process is stuck.

I did no try other authentication mechanisms as privatekey is the only one I am interested on and from there is where I found the settimeout function in the following line
https://github.com/google/earthengine-api/blob/ba57b055e1db6e0839ea9a26149e78c13ab5a73b/javascript/src/data.js#L3121

**Comment by donmccurdy** [comment] 2019-02-25 21:24
I see, thanks. The `setTimeout` is intended behavior in a browser context, but I agree that the side effects are unwanted in a NodeJS CLI context. This obviously isn't a proper fix, but if necessary you can call `process.exit(0)` to exit.

I think the right solution here would be to use [`.unref()`](https://nodejs.org/api/timers.html#timers_timeout_unref) to ensure the `setTimeout` doesn't prevent NodeJS from exiting. An alternative would be to not set a timeout at all, but this would cause authentication refreshes to happen only when a method is called, and would periodically add unnecessary latency to those calls.

**Comment by Borshick** [comment] 2019-06-26 20:44
Hi!!
I'm having the same problem and process.exit(0) doesen't works for me because i need to return a value at the end of the execution.

Is it going to be fixed at any time soon??

**Comment by donmccurdy** [comment] 2019-06-26 20:53
This will be fixed by v0.1.183, in the next few weeks I expect.

**Comment by donmccurdy** [comment] 2019-07-15 15:56
Fixed.

**Closed by donmccurdy** 2019-07-15 15:56 UTC
Labels: bug, node.js

**Comment by lleirborras** [comment] 2019-07-16 06:58
> Fixed.

Could you point me to the commit or PR with the fix?

**Comment by donmccurdy** [comment] 2019-07-16 16:29
See https://github.com/google/earthengine-api/commit/58d4d4ffef60088326d548ead26417dba959ef19#diff-c79c06e02a562beb1c3ece253206b090L3162.

**Comment by lleirborras** [comment] 2019-07-17 09:56
Thanks @donmccurdy !
